### ISSUE TITLE
Can the method be used for larger input images ? like 3x320x320 

### ISSUE THREAD

**Issue by cristyioan2000** [haihabi/GNAS#4]
I am using a `64x3x320x320` shape for the input image. It goes out of memory at the first layer, it works only at `batch_size = 2`, while using a Nvidia 1080Ti 11GB. I watched the searching algorithm for Cifar-10 with a `batch_size = 64` and the GPU reaches at 8GB in no time. No modifications made on the code this time. I believe that the current code won't work properly on a 3x320x320 input image am I right ?

**Comment by haihabi** [comment]
The network is designed for CIFAR10 and CIFAR100 image size, If you want to work with a large image size I think the first step would be to add stride to the first convolution and max-pooling layer after that (make this change in the file:https://github.com/haihabi/GeneticNAS/blob/master/models/model_cnn.py  in conv1 line 38).  
This change would reduce the input size from 320 to 80 and allow you to work with a higher batch size but still, I think you should use a bigger GPU something like the V100.

**Comment by cristyioan2000** [comment]
I tried changing the `Net(nn.Module)` structure in from `module_cnn.py` with this:
```

       ##############################
       # LAYER 1
       # In [3x320x320]
       # Out [64x160x160]
       ##############################

        self.conv1 = nn.Conv2d(3, 64, kernel_size=7, stride=2, padding=3, bias=False)
        self.bn1 = nn.BatchNorm2d(64)

        ##############################
        # CELL - NORMAL
        ##############################
        self.block_1 = RepeatBlock(64, 64, ss,
                                   individual_index=normal_block_index, first_block=first_block_index)
        ##############################
        # REDUCE DIM
        # In [64x160x160]
        # Out [64x80x80]
        ##############################
        self.avg = nn.AvgPool2d(2)

        ##############################
        # LAYER 2
        # In [64x80x80]
        # Out [128x40x40]
        ##############################
        self.conv2 = nn.Conv2d(64, 128, 1, stride=1, padding=1, bias=False)
        self.bn2 = nn.BatchNorm2d(128)

        self.conv2_prev = nn.Conv2d(64, 128, 1, stride=1, padding=1, bias=False)
        self.bn2_prev = nn.BatchNorm2d(128)
        '''
        # DISABLED
        # Shallow output 
        # Change to [128,40,40]
        '''
        # self.conv_adapt = nn.Conv2d(40,64,3, stride=4, padding=0, bias=False)
        # self.conv_adapt_prev = nn.Conv2d(40,64,3, stride=4, padding=0, bias=False)

        ##############################
        # CELL - NORMAL
        ##############################
        self.block_2_reduce = gnas.modules.CnnSearchModule(128, ss, individual_index=reduce_block_index)
        self.block_2 = RepeatBlock(n_blocks, 128, ss,
                                   individual_index=normal_block_index)

        ########################
        # self.avg_adapt = nn.AvgPool2d(kernel_size=3,stride=4,padding=0)
        # self.conv2d_adapt = nn.Conv2d(in_channels=64,out_channels=128,kernel_size=1,padding=0,stride=1)
        # self.conv2d_adapt_prev =  nn.Conv2d(in_channels=64,out_channels=128,kernel_size=1,padding=0,stride=1)
        ########################

        ##############################
        # CELL - REDUCE
        ##############################
        self.block_3_reduce = gnas.modules.CnnSearchModule(128, ss, individual_index=reduce_block_index)
        self.block_3 = RepeatBlock(n_blocks, 128, ss,
                                   individual_index=normal_block_index)
        ##############################
        # LAYER 3
        # In [128x40x40]
        # Out [512x20x20]
        ##############################
        self.conv3 = nn.Conv2d(in_channels=128,out_channels=512,kernel_size=1,padding=0,stride=1)
        self.bn3 = nn.BatchNorm2d(512)
        # Extract Shallow
        self.conv3_prev = nn.Conv2d(in_channels=128,out_channels=512,kernel_size=1,padding=0,stride=1)
        self.bn3_prev = nn.BatchNorm2d(512)

        ##########################################
        # UPSCALE BLOCK
        # [128x40x40] ---> [512x20x20]
        #self.conv2d_upscale = nn.Conv2d(in_channels=128,out_channels=512,stride=2,padding=0,kernel_size=1)

        ##########################################
        self.relu = nn.ReLU()
```
But the problem seems to be in `sub_graph_module.py`, more specific, here ` net.append(nm(net))`  :
 ```
def forward(self, *input_list):
        # input list at start is h_n and h_(n-1)
        net = list(input_list)
        for nm in self.block_modules:  # loop over all blocks
            net.append(nm(net))  # call each block in the sub graph
        return net  # output list of all block in the sub graph
```
Here the GPU goes out of memory. I think the method is to expensive for `[3x320x320]` image size, even using `kernel_size = 7` and reducing the image size to `[128x40x40]` the sub_graph_node is too expensive.

**Comment by haihabi** [comment]
Did you try the max pool with kernel size 2 and stride 2 after LAYER 1 ?

**Comment by cristyioan2000** [comment]
Yes, 
```
        ##############################
        # LAYER 1
        # In [3x320x320]
        # Out [64x160x160]
        ##############################

        x_prev = self.bn1(self.conv1(x))

        ##############################
        # MAXPOOL S = 2 ,K = [2x2]
        ##############################
        x_prev = self.max_pool_1(x_prev)
        ##############################
        # CELL - NORMAL
        # In [64x160x160]
        # Out [64x160x160]
        ##############################
        x, x_prev = self.block_1(x_prev, x_prev)
```
It always crashes here: 
```
Traceback (most recent call last):
  File "/home/lbularca/Desktop/GeneticNAS/main.py", line 227, in <module>
    shallow_deep = net(inputs)  # forward
  File "/home/lbularca/anaconda3/lib/python3.7/site-packages/torch/nn/modules/module.py", line 493, in __call__
    result = self.forward(*input, **kwargs)
  File "/home/lbularca/Desktop/GeneticNAS/models/model_cnn.py", line 160, in forward
    x, x_prev = self.block_1(x_prev, x_prev)
  File "/home/lbularca/anaconda3/lib/python3.7/site-packages/torch/nn/modules/module.py", line 493, in __call__
    result = self.forward(*input, **kwargs)
  File "/home/lbularca/Desktop/GeneticNAS/models/model_cnn.py", line 18, in forward
    x_new = b(x, x_prev)
  File "/home/lbularca/anaconda3/lib/python3.7/site-packages/torch/nn/modules/module.py", line 493, in __call__
    result = self.forward(*input, **kwargs)
  File "/home/lbularca/Desktop/GeneticNAS/gnas/modules/cnn_block.py", line 51, in forward
    net = self.sub_graph_module(inputs_tensor, bypass_input)
  File "/home/lbularca/anaconda3/lib/python3.7/site-packages/torch/nn/modules/module.py", line 493, in __call__
    result = self.forward(*input, **kwargs)
  File "/home/lbularca/Desktop/GeneticNAS/gnas/modules/sub_graph_module.py", line 26, in forward
    net.append(nm(net))  # call each block in the sub graph
  File "/home/lbularca/anaconda3/lib/python3.7/site-packages/torch/nn/modules/module.py", line 493, in __call__
    result = self.forward(*input, **kwargs)
  File "/home/lbularca/Desktop/GeneticNAS/gnas/modules/node_module.py", line 96, in forward
    return self.op_a(net_a) + self.op_b(net_b)
  File "/home/lbularca/anaconda3/lib/python3.7/site-packages/torch/nn/modules/module.py", line 493, in __call__
    result = self.forward(*input, **kwargs)
  File "/home/lbularca/Desktop/GeneticNAS/modules/drop_module.py", line 32, in forward
    self.update_tensor_shape(*input)
  File "/home/lbularca/Desktop/GeneticNAS/modules/drop_module.py", line 27, in update_tensor_shape
    output_tensor = self.module(*input)
  File "/home/lbularca/anaconda3/lib/python3.7/site-packages/torch/nn/modules/module.py", line 493, in __call__
    result = self.forward(*input, **kwargs)
  File "/home/lbularca/anaconda3/lib/pnet = self.sub_graph_module(inputs_tensor, bypass_input)ython3.7/site-packages/torch/nn/modules/container.py", line 92, in forward
    input = module(input)
  File "/home/lbularca/anaconda3/lib/python3.7/site-packages/torch/nn/modules/module.py", line 493, in __call__
    result = self.forward(*input, **kwargs)
  File "/home/lbularca/anaconda3/lib/python3.7/site-packages/torch/nn/modules/container.py", line 92, in forward
    input = module(input)
  File "/home/lbularca/anaconda3/lib/python3.7/site-packages/torch/nn/modules/module.py", line 493, in __call__
    result = self.forward(*input, **kwargs)
  File "/home/lbularca/anaconda3/lib/python3.7/site-packages/torch/nn/modules/conv.py", line 338, in forwardnet = self.sub_graph_module(inputs_tensor, bypass_input)
    self.padding, self.dilation, self.groups)
RuntimeError: CUDA out of memory. Tried to allocate 20.00 MiB (GPU 0; 10.92 GiB total capacity; 7.62 GiB already allocated; 8.94 MiB free; 1.12 GiB cached)
```
My guess is that the big input  to the `block_1` makes the crash. I debugged and `net = self.sub_graph_module(inputs_tensor, bypass_input)` is the place where the whole memory it is used.

**Comment by haihabi** [comment]
Ok, I never tried this method with this input size, what is the current maximal batch size?

**Comment by cristyioan2000** [comment]
It works only with `batch size = 1` i can see for input `[3x320x320]`. If i use a big size for kernel size and stride: `kernel size = 5x5 & stide = 5 ` for `MaxPool` after` LAYER 1` it seems to work. But i think the accuracy will be affected because the size of the image is very small, especially because i am trying to use it for detection. I think i should be using 2x GPU's for this task.

**Comment by haihabi** [comment]
It sounds good, also may be using a different a bigger GPU like the V100. please tell how this works out for you.

**Comment by cristyioan2000** [comment]
It seems to work with this setup for `[3x320x320]` input size, and after downsample using a convolutional layer and a Max Pooling layer
```
self.conv1 = nn.Conv2d(3, n_channels, kernel_size=7, stride=2, padding=3, bias=False)
        self.maxPool = nn.MaxPool2d(kernel_size=5,stride=2 )
```
 With this config:
```
{
  "batch_size": 16,
  "batch_size_val": 1000,
  "n_epochs": 610,
  "n_blocks": 1,
  "n_block_type": 3,
  "n_nodes": 3,
  "n_channels": 64 ,
  "generation_size": 20,
  "generation_per_epoch": 2,
  "full_dataset": false,
  "population_size": 20,
  "keep_size": 0,
  "mutation_p": 0.02,
  "p_cross_over": 1.0,
  "cross_over_type": "Block",
  "learning_rate": 0.001,
  "lr_min": 0.00001,
  "weight_decay": 0.0001,
  "dropout": 0.2,
  "drop_path_keep_prob": 1.0,
  "drop_path_start_epoch": 50,
  "cutout": true,
  "n_holes": 1,
  "length": 16,
  "LRType": "MultiStepLR",
  "num_class": 5,
  "momentum": 0.9,
  "aux_loss": false,
  "aux_scale": 0.4
}
```
I wonder if the "individuals" with low fitness score are kept in the population vector during each epoch. That might be a place to optimize. I am still trying to pass some errors but it seems to work.

**Comment by haihabi** [comment]
Yes, from generation to generation we keep the generation_size individuals.  You can keep only the x best but the genetic search might stack in a local minima.

**Comment by cristyioan2000** [comment]
First I want to make it work at least 5 epochs after that I will optimize the code for detection in order to increase the channel size, node number and batch size.

**Comment by haihabi** [comment]
Great, let may know how it goes.
